/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package koperasipetik;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Teza Alfian
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        produk = new javax.swing.JPanel();
        iconproduk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        anggota = new javax.swing.JPanel();
        iconproduk2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        iconproduk3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        investasi = new javax.swing.JPanel();
        iconproduk4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        peminjaman = new javax.swing.JPanel();
        iconproduk5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        belanja = new javax.swing.JPanel();
        iconproduk6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        list = new javax.swing.JPanel();
        daftarProduk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        daftarAnggota = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        header6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        add6 = new javax.swing.JButton();
        daftarTransaksi = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        header7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        add7 = new javax.swing.JButton();
        daftarInvestasi = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        header8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        add8 = new javax.swing.JButton();
        daftarPeminjaman = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        header9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        add9 = new javax.swing.JButton();
        daftarBelanja = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        header10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        add10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(66, 123, 198));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produk.setBackground(new java.awt.Color(143, 192, 247));
        produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                produkMousePressed(evt);
            }
        });

        iconproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/path2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(iconproduk);
        jLabel2.setText("Produk");

        javax.swing.GroupLayout produkLayout = new javax.swing.GroupLayout(produk);
        produk.setLayout(produkLayout);
        produkLayout.setHorizontalGroup(
            produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produkLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        produkLayout.setVerticalGroup(
            produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconproduk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidebar.add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 50));

        anggota.setBackground(new java.awt.Color(66, 123, 198));
        anggota.setPreferredSize(new java.awt.Dimension(210, 51));
        anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                anggotaMousePressed(evt);
            }
        });

        iconproduk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/g4584.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setLabelFor(iconproduk);
        jLabel4.setText("Anggota");

        javax.swing.GroupLayout anggotaLayout = new javax.swing.GroupLayout(anggota);
        anggota.setLayout(anggotaLayout);
        anggotaLayout.setHorizontalGroup(
            anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anggotaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconproduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        anggotaLayout.setVerticalGroup(
            anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconproduk2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addGroup(anggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, -1));

        transaksi.setBackground(new java.awt.Color(66, 123, 198));
        transaksi.setPreferredSize(new java.awt.Dimension(210, 51));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transaksiMousePressed(evt);
            }
        });

        iconproduk3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transaksi.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setLabelFor(iconproduk);
        jLabel5.setText("Transaksi");

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconproduk3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconproduk3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, -1));

        investasi.setBackground(new java.awt.Color(66, 123, 198));
        investasi.setPreferredSize(new java.awt.Dimension(210, 51));
        investasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                investasiMousePressed(evt);
            }
        });

        iconproduk4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/investasi.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setLabelFor(iconproduk);
        jLabel6.setText("Investasi");

        javax.swing.GroupLayout investasiLayout = new javax.swing.GroupLayout(investasi);
        investasi.setLayout(investasiLayout);
        investasiLayout.setHorizontalGroup(
            investasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investasiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconproduk4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        investasiLayout.setVerticalGroup(
            investasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconproduk4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, investasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(investasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, -1));

        peminjaman.setBackground(new java.awt.Color(66, 123, 198));
        peminjaman.setPreferredSize(new java.awt.Dimension(210, 51));
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                peminjamanMousePressed(evt);
            }
        });

        iconproduk5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/peminjaman.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setLabelFor(iconproduk);
        jLabel7.setText("Peminjaman");

        javax.swing.GroupLayout peminjamanLayout = new javax.swing.GroupLayout(peminjaman);
        peminjaman.setLayout(peminjamanLayout);
        peminjamanLayout.setHorizontalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconproduk5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        peminjamanLayout.setVerticalGroup(
            peminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconproduk5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, -1));

        belanja.setBackground(new java.awt.Color(66, 123, 198));
        belanja.setPreferredSize(new java.awt.Dimension(210, 51));
        belanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                belanjaMousePressed(evt);
            }
        });

        iconproduk6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/belanja.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setLabelFor(iconproduk);
        jLabel8.setText("Belanja");

        javax.swing.GroupLayout belanjaLayout = new javax.swing.GroupLayout(belanja);
        belanja.setLayout(belanjaLayout);
        belanjaLayout.setHorizontalGroup(
            belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(belanjaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(iconproduk6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        belanjaLayout.setVerticalGroup(
            belanjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconproduk6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, belanjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(belanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Koperasi Petik");
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, -1));

        jSeparator1.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator1.setForeground(new java.awt.Color(143, 192, 247));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 70));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 650));

        list.setBackground(new java.awt.Color(192, 217, 245));
        list.setPreferredSize(new java.awt.Dimension(20, 506));

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        background.add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 10, 650));

        daftarProduk.setBackground(new java.awt.Color(255, 255, 255));
        daftarProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        daftarProduk.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header.setBackground(new java.awt.Color(66, 123, 198));
        header.setForeground(new java.awt.Color(143, 192, 247));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("PRODUK");

        jSeparator2.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator2.setForeground(new java.awt.Color(143, 192, 247));

        jPanel2.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarProduk.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add.setBackground(new java.awt.Color(66, 123, 198));
        add.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("TAMBAH BARU");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        daftarProduk.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        daftarAnggota.setBackground(new java.awt.Color(255, 255, 255));
        daftarAnggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        daftarAnggota.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header6.setBackground(new java.awt.Color(66, 123, 198));
        header6.setForeground(new java.awt.Color(143, 192, 247));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ANGGOTA");

        jSeparator8.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator8.setForeground(new java.awt.Color(143, 192, 247));

        jPanel8.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header6Layout = new javax.swing.GroupLayout(header6);
        header6.setLayout(header6Layout);
        header6Layout.setHorizontalGroup(
            header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header6Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        header6Layout.setVerticalGroup(
            header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(header6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarAnggota.add(header6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add6.setBackground(new java.awt.Color(66, 123, 198));
        add6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add6.setForeground(new java.awt.Color(255, 255, 255));
        add6.setText("TAMBAH BARU");
        add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add6ActionPerformed(evt);
            }
        });
        daftarAnggota.add(add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        daftarTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        daftarTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        daftarTransaksi.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header7.setBackground(new java.awt.Color(66, 123, 198));
        header7.setForeground(new java.awt.Color(143, 192, 247));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("TRANSAKSI");

        jSeparator9.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator9.setForeground(new java.awt.Color(143, 192, 247));

        jPanel9.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header7Layout = new javax.swing.GroupLayout(header7);
        header7.setLayout(header7Layout);
        header7Layout.setHorizontalGroup(
            header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header7Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        header7Layout.setVerticalGroup(
            header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(header7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarTransaksi.add(header7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add7.setBackground(new java.awt.Color(66, 123, 198));
        add7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add7.setForeground(new java.awt.Color(255, 255, 255));
        add7.setText("TAMBAH BARU");
        add7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add7ActionPerformed(evt);
            }
        });
        daftarTransaksi.add(add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        daftarInvestasi.setBackground(new java.awt.Color(255, 255, 255));
        daftarInvestasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        daftarInvestasi.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header8.setBackground(new java.awt.Color(66, 123, 198));
        header8.setForeground(new java.awt.Color(143, 192, 247));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("INVESTASI");

        jSeparator10.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator10.setForeground(new java.awt.Color(143, 192, 247));

        jPanel10.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header8Layout = new javax.swing.GroupLayout(header8);
        header8.setLayout(header8Layout);
        header8Layout.setHorizontalGroup(
            header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header8Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        header8Layout.setVerticalGroup(
            header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(header8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarInvestasi.add(header8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add8.setBackground(new java.awt.Color(66, 123, 198));
        add8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add8.setForeground(new java.awt.Color(255, 255, 255));
        add8.setText("TAMBAH BARU");
        add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add8ActionPerformed(evt);
            }
        });
        daftarInvestasi.add(add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarInvestasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        daftarPeminjaman.setBackground(new java.awt.Color(255, 255, 255));
        daftarPeminjaman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        daftarPeminjaman.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header9.setBackground(new java.awt.Color(66, 123, 198));
        header9.setForeground(new java.awt.Color(143, 192, 247));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("PEMINJAMAN");

        jSeparator11.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator11.setForeground(new java.awt.Color(143, 192, 247));

        jPanel11.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header9Layout = new javax.swing.GroupLayout(header9);
        header9.setLayout(header9Layout);
        header9Layout.setHorizontalGroup(
            header9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header9Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(header9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        header9Layout.setVerticalGroup(
            header9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(header9Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarPeminjaman.add(header9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add9.setBackground(new java.awt.Color(66, 123, 198));
        add9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add9.setForeground(new java.awt.Color(255, 255, 255));
        add9.setText("TAMBAH BARU");
        add9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add9ActionPerformed(evt);
            }
        });
        daftarPeminjaman.add(add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        daftarBelanja.setBackground(new java.awt.Color(255, 255, 255));
        daftarBelanja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable11);

        daftarBelanja.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 770, 280));

        header10.setBackground(new java.awt.Color(66, 123, 198));
        header10.setForeground(new java.awt.Color(143, 192, 247));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("BELANJA");

        jSeparator12.setBackground(new java.awt.Color(143, 192, 247));
        jSeparator12.setForeground(new java.awt.Color(143, 192, 247));

        jPanel12.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header10Layout = new javax.swing.GroupLayout(header10);
        header10.setLayout(header10Layout);
        header10Layout.setHorizontalGroup(
            header10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header10Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addGroup(header10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        header10Layout.setVerticalGroup(
            header10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(header10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        daftarBelanja.add(header10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 60));

        add10.setBackground(new java.awt.Color(66, 123, 198));
        add10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add10.setForeground(new java.awt.Color(255, 255, 255));
        add10.setText("TAMBAH BARU");
        add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add10ActionPerformed(evt);
            }
        });
        daftarBelanja.add(add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 140, 30));

        background.add(daftarBelanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 830, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anggotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMousePressed
        // TODO add your handling code here:
        setColor(anggota);
        resetColor(produk);
        resetColor(transaksi);
        resetColor(peminjaman);
        resetColor(belanja);
        resetColor(investasi);
        
        daftarProduk.setVisible(false);
        daftarAnggota.setVisible(true);
        daftarBelanja.setVisible(false);
        daftarInvestasi.setVisible(false);
        daftarPeminjaman.setVisible(false);
        daftarTransaksi.setVisible(false);
    }//GEN-LAST:event_anggotaMousePressed

    private void transaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMousePressed
        // TODO add your andling code here:
        setColor(transaksi);
        resetColor(anggota);
        resetColor(produk);
        resetColor(peminjaman);
        resetColor(belanja);
        resetColor(investasi);
        
        daftarProduk.setVisible(false);
        daftarAnggota.setVisible(false);
        daftarBelanja.setVisible(false);
        daftarInvestasi.setVisible(false);
        daftarPeminjaman.setVisible(false);
        daftarTransaksi.setVisible(true);
    }//GEN-LAST:event_transaksiMousePressed

    private void investasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_investasiMousePressed
        // TODO add your handling code here:
        setColor(investasi);
        resetColor(anggota);
        resetColor(transaksi);
        resetColor(peminjaman);
        resetColor(belanja);
        resetColor(produk);
        
        daftarProduk.setVisible(false);
        daftarAnggota.setVisible(false);
        daftarBelanja.setVisible(false);
        daftarInvestasi.setVisible(true);
        daftarPeminjaman.setVisible(false);
        daftarTransaksi.setVisible(false);
    }//GEN-LAST:event_investasiMousePressed

    private void peminjamanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMousePressed
        // TODO add your handling code here:
        setColor(peminjaman);
        resetColor(anggota);
        resetColor(transaksi);
        resetColor(produk);
        resetColor(belanja);
        resetColor(investasi);
        
        daftarProduk.setVisible(false);
        daftarAnggota.setVisible(false);
        daftarBelanja.setVisible(false);
        daftarInvestasi.setVisible(false);
        daftarPeminjaman.setVisible(true);
        daftarTransaksi.setVisible(false);
    }//GEN-LAST:event_peminjamanMousePressed

    private void belanjaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belanjaMousePressed
        // TODO add your handling code here:
        setColor(belanja);
        resetColor(anggota);
        resetColor(transaksi);
        resetColor(peminjaman);
        resetColor(produk);
        resetColor(investasi);
        
        daftarProduk.setVisible(false);
        daftarAnggota.setVisible(false);
        daftarBelanja.setVisible(true);
        daftarInvestasi.setVisible(false);
        daftarPeminjaman.setVisible(false);
        daftarTransaksi.setVisible(false);
    }//GEN-LAST:event_belanjaMousePressed

    private void produkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkMousePressed
        // TODO add your handling code here:
        setColor(produk);
        resetColor(anggota);
        resetColor(transaksi);
        resetColor(peminjaman);
        resetColor(belanja);
        resetColor(investasi);
        
        daftarProduk.setVisible(true);
        daftarAnggota.setVisible(false);
        daftarBelanja.setVisible(false);
        daftarInvestasi.setVisible(false);
        daftarPeminjaman.setVisible(false);
        daftarTransaksi.setVisible(false);
    }//GEN-LAST:event_produkMousePressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add6ActionPerformed

    private void add7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add7ActionPerformed

    private void add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add8ActionPerformed

    private void add9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add9ActionPerformed

    private void add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(143,192,247));
        
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(66,123,198));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add10;
    private javax.swing.JButton add6;
    private javax.swing.JButton add7;
    private javax.swing.JButton add8;
    private javax.swing.JButton add9;
    private javax.swing.JPanel anggota;
    private javax.swing.JPanel background;
    private javax.swing.JPanel belanja;
    private javax.swing.JPanel daftarAnggota;
    private javax.swing.JPanel daftarBelanja;
    private javax.swing.JPanel daftarInvestasi;
    private javax.swing.JPanel daftarPeminjaman;
    private javax.swing.JPanel daftarProduk;
    private javax.swing.JPanel daftarTransaksi;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header10;
    private javax.swing.JPanel header6;
    private javax.swing.JPanel header7;
    private javax.swing.JPanel header8;
    private javax.swing.JPanel header9;
    private javax.swing.JLabel iconproduk;
    private javax.swing.JLabel iconproduk2;
    private javax.swing.JLabel iconproduk3;
    private javax.swing.JLabel iconproduk4;
    private javax.swing.JLabel iconproduk5;
    private javax.swing.JLabel iconproduk6;
    private javax.swing.JPanel investasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JPanel list;
    private javax.swing.JPanel peminjaman;
    private javax.swing.JPanel produk;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
